### ISSUE TITLE
Add continuous integration basic setup for the template

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder-plugin-cookiecutter#2]
Use astropy ci helpers for appveyor. Travis and circle can use directly conda commands.

Install dependencies based on a requirements.txt

**Comment by rlaverde** [comment]
I think this is a duplicated of #11 I only forget to use requirements.txt

**Comment by goanpeca** [comment]
Nope this refers to the CI inside the template not the CI of this repo

**Comment by rlaverde** [comment]
Ohh I get it, i get confused, It's a little strange to have a repo inside another :see_no_evil:

**Comment by goanpeca** [comment]
>Ohh I get it, i get confused, It's a little strange to have a repo inside another 🙈

Yep I updated the title :-)

**Comment by rlaverde** [comment]
@goanpeca Should we also add travis ci configuration? linux testing is already cover by circle-ci
