### ISSUE TITLE
Error after project configuration input prompt (Versioneer configuration)

### ISSUE THREAD

**Issue by andfoy** [spyder-ide/spyder-plugin-cookiecutter#23]
After issuing the command ``cookiecutter gh:spyder-ide/spyder-plugin-cookiecutter`` and filling up the fields with the corresponding values, the configuration routine tries to execute the command ``versioneer install`` which fails immediately, as the following stacktrace indicates:
```python
versioneer.py (0.18) installed into local tree
Now running 'versioneer.py setup' to install the generated files..
 creating spyder-terminal/_version.py
Traceback (most recent call last):
  File "versioneer.py", line 1819, in <module>
    errors = do_setup()
  File "versioneer.py", line 1713, in do_setup
    with open(cfg.versionfile_source, "w") as f:
IOError: [Errno 2] No such file or directory: u'spyder-terminal/_version.py'
``` 
Is it a error in the current version of the cookiecutter plugin?

**Comment by rlaverde** [comment]
Yes, I'm aware of this bug, I noticed while doing #20, I'll make a PR to fix it.
