### ISSUE TITLE
Configure pyup bot to track dependencies updates

### ISSUE THREAD

**Issue by rlaverde** [spyder-ide/spyder-plugin-cookiecutter#27]
I'm aware this is a pip tool and we use conda, but It works with `requirements` files so It'll work.

Also this tracks packages form [pip](https://pypi.python.org/), but I don't see this as a issue, instead It'll also help us know when a package have already a new version in `pip` and not in `conda`

@goanpeca what do you think?

https://pyup.io/

**Comment by jitseniesen** [comment]
Does this mean that everybody who uses the cookie to write a plugin has to use pyup?

**Comment by rlaverde** [comment]
> Does this mean that everybody who uses the cookie to write a plugin has to use pyup?

No, I'll just be for the cookie repo, the generated repo won't include any pyup stuff

Also, I'm not sure if include pyup could be a good idea, because it pin dependencies (==)
